# Generated by Django 5.2.1 on 2025-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
